"""Business logic for email composition and delivery."""

import logging
from typing import Optional

from jinja2 import Environment, FileSystemLoader, select_autoescape

from meeting_agent.core.config import settings
from meeting_agent.core.exceptions import EmailSendError
from meeting_agent.infrastructure.database.repositories.email_log_repo import SqlEmailLogRepository
from meeting_agent.infrastructure.database.repositories.meeting_repo import SqlMeetingRepository
from meeting_agent.infrastructure.database.repositories.summary_repo import SqlSummaryRepository
from meeting_agent.infrastructure.database.repositories.task_repo import SqlTaskRepository

logger = logging.getLogger(__name__)

# Simple inline email templates (no file dependency)
TEXT_TEMPLATE = """Meeting Summary: {{ meeting_title }}
{{ "=" * (meeting_title|length + 19) }}

{{ summary.summary_text }}

Key Points:
{% for point in summary.key_points %}  • {{ point }}
{% endfor %}

Decisions:
{% for decision in summary.decisions %}  • {{ decision }}
{% endfor %}

Action Items:
{% for task in tasks %}  • {{ task.title }}{% if task.assignee_name %} ({{ task.assignee_name }}){% endif %}{% if task.due_date %} — Due: {{ task.due_date }}{% endif %}
{% endfor %}

{% if custom_message %}
Note: {{ custom_message }}
{% endif %}
---
Generated by AI Meeting Agent
"""

HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head><style>
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #333; max-width: 640px; margin: 0 auto; padding: 20px; }
h1 { color: #1a1a2e; border-bottom: 2px solid #0f3460; padding-bottom: 10px; }
h2 { color: #0f3460; margin-top: 24px; }
ul { padding-left: 20px; }
li { margin-bottom: 6px; }
.task { background: #f8f9fa; padding: 8px 12px; border-left: 3px solid #0f3460; margin-bottom: 8px; }
.task .assignee { color: #6c757d; font-size: 0.9em; }
.footer { margin-top: 30px; padding-top: 15px; border-top: 1px solid #dee2e6; color: #6c757d; font-size: 0.85em; }
.custom-msg { background: #e8f4fd; padding: 12px; border-radius: 6px; margin: 16px 0; }
</style></head>
<body>
<h1>📋 {{ meeting_title }}</h1>

<h2>Summary</h2>
<p>{{ summary.summary_text }}</p>

{% if summary.key_points %}
<h2>🔑 Key Points</h2>
<ul>
{% for point in summary.key_points %}<li>{{ point }}</li>{% endfor %}
</ul>
{% endif %}

{% if summary.decisions %}
<h2>✅ Decisions</h2>
<ul>
{% for decision in summary.decisions %}<li>{{ decision }}</li>{% endfor %}
</ul>
{% endif %}

{% if tasks %}
<h2>📝 Action Items</h2>
{% for task in tasks %}
<div class="task">
<strong>{{ task.title }}</strong>
{% if task.description %}<br><span>{{ task.description }}</span>{% endif %}
{% if task.assignee_name %}<div class="assignee">👤 {{ task.assignee_name }}{% if task.assignee_email %} ({{ task.assignee_email }}){% endif %}</div>{% endif %}
{% if task.due_date %}<div class="assignee">📅 Due: {{ task.due_date }}</div>{% endif %}
</div>
{% endfor %}
{% endif %}

{% if custom_message %}
<div class="custom-msg">{{ custom_message }}</div>
{% endif %}

<div class="footer">Generated by <strong>AI Meeting Agent</strong></div>
</body>
</html>"""


class EmailService:
    """Composes and sends meeting summary emails."""

    def __init__(
        self,
        email_log_repo: SqlEmailLogRepository,
        meeting_repo: SqlMeetingRepository,
        summary_repo: SqlSummaryRepository,
        task_repo: SqlTaskRepository = None,
        email_provider=None,
    ):
        self.email_log_repo = email_log_repo
        self.meeting_repo = meeting_repo
        self.summary_repo = summary_repo
        self.task_repo = task_repo
        self.email_provider = email_provider

    async def send_summary_email(
        self,
        meeting_id: str,
        recipients: list[str],
        custom_message: Optional[str] = None,
    ) -> dict:
        """Compose and send a meeting summary email."""
        # 1. Gather data
        meeting = await self.meeting_repo.get_by_id(meeting_id)
        if not meeting:
            raise EmailSendError(f"Meeting {meeting_id} not found")

        summary = await self.summary_repo.get_by_meeting_id(meeting_id)
        if not summary:
            raise EmailSendError(f"No summary found for meeting {meeting_id}")

        tasks = []
        if self.task_repo:
            tasks = await self.task_repo.get_by_meeting_id(meeting_id)

        # 2. Render email content
        from jinja2 import Template

        context = {
            "meeting_title": meeting.get("title", "Meeting Summary"),
            "summary": summary,
            "tasks": tasks,
            "custom_message": custom_message,
        }

        text_body = Template(TEXT_TEMPLATE).render(**context)
        html_body = Template(HTML_TEMPLATE).render(**context)

        subject = f"Meeting Summary: {meeting.get('title', 'Meeting')}"

        # 3. Log the email attempt
        email_log = await self.email_log_repo.create(
            meeting_id=meeting_id,
            recipients=recipients,
            subject=subject,
        )

        # 4. Send via provider
        if not self.email_provider:
            await self.email_log_repo.mark_failed(
                email_log["id"], "No email provider configured"
            )
            raise EmailSendError("No email provider configured")

        try:
            provider_id = await self.email_provider.send_email(
                to=recipients,
                subject=subject,
                html_body=html_body,
                text_body=text_body,
            )
            result = await self.email_log_repo.mark_sent(email_log["id"], provider_id)
            logger.info("Sent summary email for meeting %s to %s", meeting_id, recipients)
            return result
        except Exception as e:
            await self.email_log_repo.mark_failed(email_log["id"], str(e))
            raise EmailSendError(f"Failed to send email: {e}") from e

    async def get_email_history(self, meeting_id: str) -> list[dict]:
        """Get all email logs for a meeting."""
        return await self.email_log_repo.get_by_meeting_id(meeting_id)
